#!/usr/bin/env bash
# Generated by background-agents bridge. Provisions a GitHub token so `gh` works
# without interactive auth, then execs the real gh.
set -euo pipefail
GITHUB_TOKEN="$({{ .Exe }} git-credential gh-token)"
export GITHUB_TOKEN
# Drop this wrapper's directory (the first PATH entry) so command -v finds the
# real gh.
PATH="${PATH#*:}"
exec "$(command -v gh)" "$@"
