#!/bin/sh
# Generated by background-agents bridge. Git runs this in place of ssh-keygen
# (gpg.ssh.program) so commit signatures are brokered by the control plane; the
# signing key never enters the sandbox. Anything that is not a signing request
# is passed through to the real ssh-keygen by the bridge.
exec {{ .Exe }} git-sign "$@"
