package sandbox

import (
	"embed"
	"encoding/json"
	"fmt"
	"path"
	"sort"
	"strings"
)

// The bridge is the single source of truth for OpenCode tools. Each tool is
// authored under tooldefs/<name>.js as a full `export default tool({ ... })`
// module (name, agent description, zod arg schema, and execute). The module
// relies on the shim in tool_definition.js to supply the `tool` and `z` imports,
// the BRIDGE_BIN constant, and the runBridgeTool helper — so it is not run
// standalone. `bridge install` appends each module to the shim and writes the
// result to ~/.config/opencode/tools/<name>.js, which shells back into
// `bridge tool <name>`.
//
// Tool names are derived from the fragment filenames and must match the
// toolImpls dispatch table in tools.go (enforced by a test).

// toolJSTemplate is the OpenCode tool shim with __BRIDGE_* placeholders that
// generateToolJS substitutes per tool. Kept as a real .js file so editors
// lint/format it; it is not run as-is.
//
//go:embed tool_definition.js
var toolJSTemplate string

// toolDefsFS holds the per-tool definition fragments.
//
//go:embed tooldefs/*.js
var toolDefsFS embed.FS

const toolDefsDir = "tooldefs"

// generatedHeader is the standard "do not edit" banner prepended to every
// rendered tool file. The template and fragments carry their own contributor
// notes; those are stripped so only this banner survives into the output.
const generatedHeader = "// Code generated by bridge. DO NOT EDIT.\n"

// generateToolJS renders the .js source for one tool, embedding the absolute
// path to the bridge binary so the shim invokes the same binary that wrote it.
func generateToolJS(name, exePath string) (string, error) {
	frag, err := toolDefsFS.ReadFile(path.Join(toolDefsDir, name+".js"))
	if err != nil {
		return "", fmt.Errorf("read tool definition %q: %w", name, err)
	}
	shim := strings.NewReplacer(
		"__BRIDGE_BIN__", jsString(exePath),
		"__BRIDGE_TOOL_DEF__", strings.TrimRight(stripLeadingComment(string(frag)), "\n"),
	).Replace(stripLeadingComment(toolJSTemplate))
	return generatedHeader + shim, nil
}

// stripLeadingComment drops the leading `//` comment block (the fragment's
// authoring note) so it does not leak into the generated tool file.
func stripLeadingComment(s string) string {
	lines := strings.SplitAfter(s, "\n")
	i := 0
	for i < len(lines) && strings.HasPrefix(strings.TrimSpace(lines[i]), "//") {
		i++
	}
	return strings.Join(lines[i:], "")
}

// jsString returns a JS/JSON string literal for s.
func jsString(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

// toolDefNames returns the generated tool names in stable order.
func toolDefNames() []string {
	entries, err := toolDefsFS.ReadDir(toolDefsDir)
	if err != nil {
		panic(fmt.Sprintf("read embedded %s: %v", toolDefsDir, err)) // embedded; cannot fail at runtime
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		names = append(names, strings.TrimSuffix(e.Name(), ".js"))
	}
	sort.Strings(names)
	return names
}

// fileNameFor returns the .js filename for a tool.
func fileNameFor(name string) string {
	return strings.TrimSuffix(name, ".js") + ".js"
}
