package sandbox

import (
	"strings"
	"testing"
)

// TestToolDefsMatchImpls ensures every generated tool definition has an executor
// and vice versa — the JS shim and the CLI dispatch must stay in lockstep.
func TestToolDefsMatchImpls(t *testing.T) {
	defs := strings.Join(toolDefNames(), ",")
	impls := strings.Join(ToolNames(), ",")
	if defs != impls {
		t.Fatalf("toolDefs (%s) != toolImpls (%s)", defs, impls)
	}
}

func TestGenerateToolJS(t *testing.T) {
	js, err := generateToolJS("create-pull-request", "/usr/local/bin/bridge")
	if err != nil {
		t.Fatalf("generateToolJS: %v", err)
	}

	// Output leads with the generated banner, not the template's contributor note.
	if !strings.HasPrefix(js, "// Code generated by bridge. DO NOT EDIT.\n") {
		t.Errorf("generated JS missing DO NOT EDIT banner\n---\n%s", js)
	}
	if strings.Contains(js, "Template for the OpenCode tool shim") {
		t.Errorf("template contributor header leaked into generated JS\n---\n%s", js)
	}

	for _, want := range []string{
		`const BRIDGE_BIN = "/usr/local/bin/bridge";`,
		`name: "create-pull-request",`,
		`spawn(BRIDGE_BIN, ["tool", name]`,
		`return await runBridgeTool("create-pull-request", args);`,
		`import { tool } from "@opencode-ai/plugin";`,
		`baseBranch: z`,
	} {
		if !strings.Contains(js, want) {
			t.Errorf("generated JS missing %q\n---\n%s", want, js)
		}
	}

	// The fragment's authoring comment must not leak into the generated file.
	if strings.Contains(js, "Not a standalone module") {
		t.Errorf("fragment authoring comment leaked into generated JS\n---\n%s", js)
	}

	// The tool is bound to the session repo: it must name that path in its
	// description and must NOT expose a caller-supplied directory arg.
	if !strings.Contains(js, defaultRepoDir()) {
		t.Errorf("description missing repo path %q\n---\n%s", defaultRepoDir(), js)
	}
	if strings.Contains(js, "__BRIDGE_DEFAULT_REPO_DIR__") {
		t.Errorf("repo dir placeholder not substituted\n---\n%s", js)
	}
	if strings.Contains(js, "directory: z") {
		t.Errorf("create-pull-request should not expose a directory arg\n---\n%s", js)
	}
}

// TestSpawnChildDescriptionExcludesSubtasks guards the wording that keeps the
// model from reading "sub-agent"/"sub-task" — in-process task delegation — as a
// request for a child session in its own sandbox. Spawning one is expensive and
// unattended, so the description has to lead with the opt-in, name the terms
// that are not it, and say that discussing child sessions is not asking for one.
func TestSpawnChildDescriptionExcludesSubtasks(t *testing.T) {
	js, err := generateToolJS("spawn-child", "/bin/bridge")
	if err != nil {
		t.Fatalf("generateToolJS: %v", err)
	}
	for _, want := range []string{
		"Use this tool ONLY when the user's current request explicitly and affirmatively asks",
		"'sub-agent', 'subagent', 'sub agent', 'sub-task', 'subtask', or Task tool requests",
		"use the Task tool for those in-process delegations instead.",
		"Merely mentioning, comparing, or rejecting child sessions does not authorize this tool.",
	} {
		if !strings.Contains(js, want) {
			t.Errorf("spawn-child description missing %q\n---\n%s", want, js)
		}
	}
}

// TestCreatePRDescribesMultiplePullRequests guards the one-PR-per-branch
// contract in the prose. A session may open several pull requests, and the
// model can only pick between updating and opening one if the tool says which
// action a repeat call takes.
func TestCreatePRDescribesMultiplePullRequests(t *testing.T) {
	js, err := generateToolJS("create-pull-request", "/bin/bridge")
	if err != nil {
		t.Fatalf("generateToolJS: %v", err)
	}
	for _, want := range []string{
		"Calling it again from the same branch updates that branch's open pull request",
		"create a new branch with",
		"For a stacked pull request, pass the head branch of the pull request you are stacking on.",
	} {
		if !strings.Contains(js, want) {
			t.Errorf("create-pull-request description missing %q\n---\n%s", want, js)
		}
	}
}

// TestSpawnChildReasoningSpellsXhigh guards the reasoning-effort wording. The
// control plane rejects an unrecognized value outright, so the tool has to name
// the accepted ones and pin the spelling the model otherwise guesses wrong.
func TestSpawnChildReasoningSpellsXhigh(t *testing.T) {
	js, err := generateToolJS("spawn-child", "/bin/bridge")
	if err != nil {
		t.Fatalf("generateToolJS: %v", err)
	}
	for _, want := range []string{
		"'none', 'low', 'medium', 'high', 'xhigh', and 'max'",
		"Use 'xhigh', not 'x-high'.",
	} {
		if !strings.Contains(js, want) {
			t.Errorf("spawn-child reasoning description missing %q\n---\n%s", want, js)
		}
	}
}

func TestGenerateToolJSAllTools(t *testing.T) {
	// Every fragment must render and carry its name and the bridge bin.
	for _, name := range toolDefNames() {
		js, err := generateToolJS(name, "/bin/bridge")
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if !strings.Contains(js, "name: "+jsString(name)+",") {
			t.Errorf("%s: name not present/encoded", name)
		}
		if !strings.Contains(js, `const BRIDGE_BIN = "/bin/bridge";`) {
			t.Errorf("%s: bridge bin not substituted", name)
		}
		if strings.Contains(js, "__BRIDGE_") {
			t.Errorf("%s: unsubstituted placeholder remains:\n%s", name, js)
		}
	}
}
